// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMGhLxF4mgR0YM37I2yICTQsz1zcDx1pE',
    appId: '1:664487319130:web:d43c8ce9ae85681ea3aa63',
    messagingSenderId: '664487319130',
    projectId: 'market-98de7',
    authDomain: 'market-98de7.firebaseapp.com',
    storageBucket: 'market-98de7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQ8xIshaOn9DltkaYDottPAUzav26FX0',
    appId: '1:664487319130:android:eec6f2419c8abe66a3aa63',
    messagingSenderId: '664487319130',
    projectId: 'market-98de7',
    storageBucket: 'market-98de7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWuKjTmOmqUJRkU52E0rtCKktN1dPtPpM',
    appId: '1:664487319130:ios:1ef31899f50a8005a3aa63',
    messagingSenderId: '664487319130',
    projectId: 'market-98de7',
    storageBucket: 'market-98de7.firebasestorage.app',
    iosBundleId: 'com.example.market',
  );
}
